### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by PaulFelz** [ammendola/Aufgabe#1]
Ein Testticket.

Gliederung ist super!
Auf ein großartiges Tandem!

Viele Grüße
Paul Felz

**Comment by ammendola** [comment]
Lieber Paul,

ich habe nun meine Gliederung etwas mit Inhalt gefüllt und möchte Dich bitten, einmal zu schauen, ob Dir etwas auffällt, was zu verbessern wäre. Die Beispiele fehlen noch, alles andere steht nun in einer ersten Version.

Beste Grüße, Partner
Andrea

**Comment by PaulFelz** [comment]
Hochgeschätzter Tandempartner, 

was ein Prachttext!
Ich hoffe dieser kurze Hinweis ist hilfreich und ich kann dir gute Anregungen für deinen schon ziemlich gut recherchierten und fundierten Text geben.

Ich spare mir die Korrektur von den wenigen, sowieso eher unwichtigen Rechtschreibfehlern, da es ja eine Arbeit in der Entwicklung ist! Ich konzentriere mich nur auf den Inhalt. Rechtschreibfehler lassen sich dahingehend wohl besser später mit dem Pull Request bearbeiten und darstellen. :)

Es wird deutlich das du intensive Gespräche mit der IT Abteilung hattest. Mein Vorschlag bzw. meine Anmerkung für einige deiner Darstellungen, wäre sie entsprechend zu kürzen. Es könnte hierbei gut funktionieren mehr mit Links zu arbeiten. Denn so können Leser*innen deine technischen Erläuterungen und deine Bezeichnungen entweder "überlesen" wenn sie den Fachbegriff bzw. den Sachverhalt bereits kennen, was bei Herrn Förstner mit Sicherheit eher der Fall ist, oder auf den Link klicken, was bei mir sehr viel häufiger der Fall sein wird, wenn sich zu deinen Aussagen Fragen ergeben. Es gilt natürlich zu prüfen, ob dies in jedem Fall möglich ist.

Sehr gut gelungen bzw. genau diese Vorgehensweise hat mir gerade beim Lesen für Visual Library (VL) und Multidotscan sehr geholfen. 
Als weitere Beispiele, in denen es zumindest mir sehr helfen würde, seien genannt:
Die Erwähnung des Begriffs in Klammern "PostgreSQL".
Ist es die Open Source Datenbank hinter folgendem Link?
https://www.postgresql.org/

"Primo Central der Fa. Exlibris" steht auch in Klammern, ist es dieses System? https://de.wikipedia.org/wiki/Primo_Central

Auch die OAI-Schnittstelle? Ist, nehme ich an, diese hier für: http://www.openarchives.org/

Diese Beispiele sollen nur als erste Anregungen bzw. Gedanken zu deinen Aussagen dienen, die zumindest für meinen Kenntnisstand, einer kurzen Erläuterung bedürfen. Es gibt noch weitere, wenn du möchtest, kann ich diese in einem zweiten Issue auflisten. Jedoch ist dies selbstverständlich nur ein Vorschlag, den ich sehr gern zur Diskussion stelle.

Nicht zuletzt möchte ich als weiteres Argument noch erwähnen, dass manche Links auch dafür sorgen könnten, dass du an anderen Stellen kürzen kannst, um deine Erläuterungen eher einer verlinkten Website zu überlassen.

Viele Grüße
paul
