### ISSUE TITLE
Auswahl des Beispiel-Projektes

### ISSUE THREAD

**Issue by konrad** [ammendola/Aufgabe#5]
Hauptvorschlag von  @ammendola  war die Zeitungsdigitalisierung, der im [Dokument](https://github.com/ammendola/Aufgabe_MALIS_18.3_WPM_T9.1/blob/master/README.md) beschrieben wurde. Alternative wäre der andere genannte ESA-Optimierungsvorschlag.

**Comment by konrad** [comment]
Ich halte den Zeitungsdigitalisierung-Workflow für eine gute und machbare Aufgabe.

**Comment by ammendola** [comment]
Vielen Dank für die Rückmeldung. Können Sie mir vielleicht schon sagen, in welche Lösungstechniken ich mich für die zweite Aufgabe einlesen soll? Reicht es hierfür, mir anzuschauen, wie Batch-Dateien aufgebaut sind? Vielleicht haben Sie ja noch Tipps für mich, wie ich hier am besten vorgehe.

Die anderen Bilder habe ich übrigens auch nun mit ![Ordner Struktur] direkt sichtbar geschaltet. Danke für den Hinweis!

**Comment by ammendola** [comment]
Mir ist heute klar geworden, dass sich der Text in ![Ordner Struktur] nur auf das letzte Bild bezieht. Daher habe ich die Texte innerhalb der Klammern der anderen Bilder entsprechend angepasst.
