### ISSUE TITLE
Upload von zip-Dateien

### ISSUE THREAD

**Issue by PaulFelz** [ammendola/Aufgabe#6]
Hallo Partner, :)

für mich gibt es im letzten Teil einige fehlende Einzelheiten, die mir helfen würden dein Projekt besser zu verstehen und eventuell Anregungen zu geben.

Hast du Zugriff auf die Daten im bzw. auf dem Upload-Server? 
Kannst du sehen wie groß der Ordner vom Upload-Server ist? 
 Zumindest von deinen Screenshots her, würde ich annehmen, dass es problemlos möglich ist diese Infos einzusehen.

Du schreibst konkret: "In dieser Batch-Datei müsste außerdem programmiert werden, dass ZIP-Dateien nur bis zu einer noch zu definierenden Größe in den Upload-Server hochgeladen werden dürfen, um diesen nicht „volllaufen“ zu lassen."

Also geht es darum, das sich sonst zu viele zip Dateien im Upload-Server befinden und der Ordner auf dem Server zu groß wird? 
Oder dürfen zip-Dateien nur eine bestimmte Größe haben, damit sie hochgeladen werden dürfen?
Was genau bedeutet "vollaufen" in diesem Kontext? 
Ist der Speicher irgendwann ausgereizt? 
Wer leert diesen zip-Ordner eigentlich und in welchen Abständen? Also wie ist der nächtliche Batch Prozess der die zips entpackt und hochlädt gestaltet? Und kann der Prozess parallel laufen, während noch Daten hochgeladen werden? Also könntest du, sobald der nächtlche Batch Prozess gestartet hat, deine batch Datei so gestalten, dass, sobald der Ordner leerer wird,weitere zips hochgeladen werden?

Mein konkreter Gedanke dahinter ist, wäre es nicht sinnvoller, statt die zips zu prüfen, den Ordner selbst zu prüfen? Als Beispiel: Wenn der Ordner nur 6GB groß sein darf und schon 5GB Daten enthält, dann wird erst wieder ab 3GB hochgeladen, da der Ordner ab 5GB anfängt "vollzulaufen", da er nur 6GB groß sein darf. Also nur 6GB Speicher zur Verfügung steht. 

Ich hoffe ich habe die Idee hinter deiner Batch Datei richtig verstanden und du kannst mit meinem Gedankenspiel etwas anfangen.

VG
paul

**Comment by ammendola** [comment]
Servus Paul,

ja, ich habe zwar Zugriff, aber im Moment ist der Mitarbeiter, der mit dem Ordner täglich zu tun hat, nicht da. Er kommt erst morgen wieder und dann werde ich ihn direkt fragen, wie groß der Ordner ist.

Das bringt mich zu deiner Frage bzw. Anregung. Ich hatte mir das in der Tat genau so gedacht wie Du. Denn an der Größe der zip-Dateien können wir gar nicht viel schrauben, da die Zeitungstitel unterschiedlich groß sind und wir sie so importieren müssen, wie sie nun mal sind. Bedeutet, dass Du genau richtig liegst und wir die Batch-Datei so anlegen müssen, dass der Ordner selbst nicht vollläuft, sondern ab einer gewissen Grenze sagt: Stop! Erst bitte wieder Dateien rauslöschen und erst dann wieder hochladen! Ich bin mir sicher, dass der Ordner deutlich größer sein wird als nur 6 GB (wir bewegen uns im Projekt auf Terabyte-Ebene), aber das war ja nur ein Rechenexempel von Dir, der das Prinzip aber genau erfasst hat. Ich denke, ich werde das gleich im Text noch etwas klarer in diese Richtung formulieren.

Vielen Dank für die Anregung. Ich hoffe, Du verstehst jetzt besser, was ich vorhabe.

Dein Tandempartner

**Comment by ammendola** [comment]
Habe den Text im letzten Absatz jetzt umformuliert. Schau mal, ob er jetzt verständlicher ist.

Viele Grüße
A.

**Comment by PaulFelz** [comment]
Lieber A., 

genau so!
Jetzt ist der Text auch für mich viel verständlicher!
Dein Gedankengang war also schon auf dem richtigen Weg.

Wenn du Rücksprache gehalten hast, freue ich mich zu hören ob das so möglich ist. 

VG
paul

**Comment by ammendola** [comment]
Habe gerade mit meinem Mitarbeiter gesprochen und er weiß auch nicht ganz genau, wie groß der Speicher des Upload-Verzeichnisses ist (die Anfrage an die Firma semantics ist aber schon raus). Er sagte mir, dass er locker 250-300 GB auf einmal hochladen kann und es läuft so durch. Allerdings sagte er mir, dass er auch mal 500 GB auf einmal hochgeladen hat, was mit Blick auf den Speicher kein Problem war. Allerdings war der Upload-Prozess am nächsten Morgen noch nicht fertig, sodass unsere SHK erst warten mussten, bis die Dateien hochgeladen waren, bevor sie mit der Arbeit im VL-Manager anfangen konnten. Das war also ein ähnliches Problem wie mit deinen Updates im _log in_, wenn die nächste Veranstaltung dadurch verzögert wird, richtig?

Wie auch immer: Zu geringer Speicher ist wohl eher nicht das Problem (da dürften ein paar Terabyte vorrätig sein, wir werden es bald wissen), sondern eher die Geschwindigkeit beim Uploaden. Hier scheinen max. 300 GB für einen nächtlichen Upload eine gute Zahl zu sein. Das könnte man dann auch so in die Batch-Datei schreiben: Lade maximal 300 GB pro mal hoch!

Zum Schluss: Mein Mitarbeiter sagte mir, dass der Ordner nach einer Woche die vorhandenen ZIP-Dateien löscht, sodass sich allein hierdurch die Speicherfrage erübrigt. Man könnte das trotzdem ja (als Übung für mich) nochmal coden. Oder was meinst Du?

Es macht übrigens mega fun hier alles!

A.

**Comment by ammendola** [comment]
So, habe jetzt am Ende meines Textes noch zwei Sätze zu der Datenbegrenzung pro Upload hinzugefügt. Läuft...

A.

**Comment by ammendola** [comment]
So, mein Lieber Paul,

nun habe ich endlich Nachricht von der Fa. semantics, die mir folgendes zu meiner Frage nach einer physikalischen Begrenzung des Plattenplatzes im Upload-Bereich schreibt:

> Im Importbereich könnten derzeit max. 10 TB hochgeladen und verarbeitet werden. Wobei sich das Platzangebot wieder in dem Maß erneuert, wie Importe abgearbeitet wurden. Im Speicherbereich, in dem die TIFFs abgelegt werden, stehen derzeit > 30 TB zur Verfügung - aber der Platz kann natürlich bei Bedarf erweitert werden.

Das hört sich also wie vermutet nicht nach einem Speicherproblem an, sondern eher nach der zeitlichen Dimension eines Uploads, den ich für mein Beispiel als automatischen Prozess mit einer GB-Begrenzung pro Upload coden müsste.

Ich schließe also das Ticket, Du kannst aber gerne noch was zu anmerken.

VG
A,
