### ISSUE TITLE
Markdown Syntax und Zitate

### ISSUE THREAD

**Issue by PaulFelz** [ammendola/Aufgabe#7]
Lieber A.,

da unser Dokument in Markdown geschrieben ist, denke ich, wäre auch die Syntax von Markdown für Zitate zu verwenden. 
Denke dies ist Geschmackssache und keine Frage der Wissenschaftlichkeit, deine Anführungszeichen sind eindeutige Hinweise.
Aber theoretisch wird bspw. für Zitate in Markdown die spitze Klammer verwendet.
https://markdown.de/ --siehe Abschnitt Zitate im oberen Drittel der Seite
https://de.wikipedia.org/wiki/Markdown

Zugegeben; dies ist wirklich kaum der Rede wert, aber was denkst du? :)

VG
paul

**Comment by ammendola** [comment]
Du hast natürlich völlig recht, werter Tandempartner!

Ich habe Deinen Hinweis nun in die Tat umgesetzt. Schau mal, es sieht jetzt so viel besser aus, oder?

Beste Grüße
A.

**Comment by PaulFelz** [comment]
Jau! 
Das sieht viel besser aus und nutzt die Funktionen von Markdown!
Perfekt! 

:+1: 
:100: 
:1st_place_medal:

**Comment by ammendola** [comment]
Danke!
